### ISSUE TITLE
neutralino-win_x64.exe error code 1

### ISSUE THREAD

**Issue by rxmarccall** [codezri/litepy#4]
Hello,
I've downloaded the project and am attempting to run the project by using `neu run` but I end up getting the following messaging:

> Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-win_x64.exe was stopped with error code 1

Any idea why I'm getting this error? Really I'm just looking for a template project of NeutralinoJs + React and was hoping I could use this project.

**Comment by shalithasuranga** [comment]
This project has been updated by fixing several issues and using the latest framework version. Also, this project was tested again and the above mentioned issue didn't occur. Please check the latest commit of this project :tada: thanks for reporting this bug
