### ISSUE TITLE
`yarn run build` failed!

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [codezri/litepy#7]
## Description
The project fails to build after installation of all dependencies using Yarn. 

## Image 
![image](https://github.com/codezri/litepy/assets/72215925/ee5b318c-a67f-411b-80d3-8963fdac448b)

## Environment
Operating System : Arch Linux
Yarn Version : 1.22.21

## Potential Issue
`react-scripts` seems to be the point of error. Not sure a 100%. Would like some help in building and trying out the application. Thank You.

**Comment by shalithasuranga** [comment]
This project has been updated by fixing several issues and using the latest framework version. Also, this project was tested again and the above mentioned issue didn't occur. Please check the latest commit of this project 🎉 thanks for reporting this bug
